---

acme_packages:
  - acme.sh

acme_user: acme
acme_group: acme
acme_home: /var/db/acme
acme_log_path: /var/log/acme
acme_test: yes

acme_script_name: "dns_{{ acme_dns }}_ansible"
acme_script_path: "{{ acme_home }}/.acme.sh/{{ acme_script_name }}.sh"

acme_cert_home: "{{ acme_home }}/certs"
acme_cert_file: "{{ acme_cert_home }}/{{ hostname }}/fullchain.cer"
acme_log_file: "{{ acme_log_path }}/acme.sh.log"

acme_install_path: /etc/acme.sh
acme_install_path_owner: "{{ acme_user }}"
acme_install_path_group: mail
acme_install_key_file: "{{ acme_install_path }}/{{ hostname }}/key.pem"
acme_install_cert_file: "{{ acme_install_path }}/{{ hostname }}/cert.pem"
acme_install_fullchain_file: "{{ acme_install_path }}/{{ hostname }}/fullchain.pem"

acme_env: []
acme_dns: ""
acme_dnssleep: no
