---

- name: Echo domain name
  debug:
    var: domain

- name: Generate dkim private key for domain
  shell:
    cmd: "rspamadm dkim_keygen -s '{{ dkim_selector }}' -b {{ dkim_key_size }} -d {{ domain }} -k '{{ dkim_path }}/{{ dkim_selector }}.{{ domain }}.key' >{{ dkim_path }}/{{ domain }}.txt"
    creates: "{{ dkim_path }}/{{ domain }}.txt"
  notify:
    - restart rspamd

- name: Update dns zone file with spf and dmarc records
  lineinfile:
    path: "{{ dkim_path }}/{{ domain }}.txt"
    line: "{{ zone_line.text }}"
    regexp: "{{ zone_line.regexp }}"
  loop:
    - text: "@ IN TXT \"v=spf1 mx -all\""
      regexp: "v=spf1"
    - text: "_dmarc IN TXT \"v=DMARC1; p=reject;\""
      regexp: "^_dmarc"
  loop_control:
    loop_var: zone_line

- name: Set proper dkim private key permissions
  file:
    path: "{{ dkim_path }}/{{ dkim_selector }}.{{ domain }}.key"
    mode: "{{ dkim_keyfile_mode }}"

- name: Fetch dns zone file
  fetch:
    src: "{{ dkim_path }}/{{ domain }}.txt"
    dest: dns/{{ domain }}.txt
    flat: yes
